# Makefile in zlib

LIB=$(LIB_ZLIB)

CFILES=src/adler32.c src/compress.c src/crc32.c src/deflate.c src/gzio.c \
	src/infback.c src/inffast.c src/inflate.c src/inftrees.c src/trees.c \
	src/uncompr.c src/zutil.c

INCLUDES=

include $(TOP)/make_lib.mk
