# Makefile in MeshCompiler

PROGRAM=mMeshCompiler$(EXE)

INST_EXTRA=$(INST_EXTRA_DIR)

CXXFILES=src/main.cpp src/meshcompiler.cpp

INCLUDES=$(INC_3D) $(INC_MATH) $(INC_CORE)

LIBRARIES=$(LIB_3D) $(LIB_MATH) $(LIB_CORE) $(LIB_ZLIB)

include $(TOP)/make_prg.mk
