# Makefile in UI

LIB=$(LIB_UI)

CXXFILES=src/Actions/wbactionuipushscreen.cpp src/Actions/wbactionuisetwidgetimage.cpp \
	src/Actions/wbactionuishowhidewidget.cpp src/Actions/wbactionuishowyesnodialog.cpp \
	src/Common/uimanagercommon.cpp src/Screens/uiscreen-base.cpp \
	src/Screens/uiscreen-fade.cpp src/Screens/uiscreen-okdialog.cpp \
	src/Screens/uiscreen-waitdialog.cpp src/Screens/uiscreen-yesnodialog.cpp \
	src/uifactory.cpp src/uimanager.cpp src/uiscreen.cpp src/uistack.cpp \
	src/uiwidget.cpp src/Widgets/uiwidget-composite.cpp src/Widgets/uiwidget-frame.cpp \
	src/Widgets/uiwidget-image.cpp src/Widgets/uiwidget-slider.cpp \
	src/Widgets/uiwidget-spacer.cpp src/Widgets/uiwidget-text.cpp \
	src/Widgets/uiwidget-input.cpp src/Widgets/uiwidget-scrollbar.cpp \
	src/Widgets/uiwidget-list.cpp src/Screens/uiscreen-selectfiledialog.cpp

INCLUDES=$(INC_CORE) $(INC_MATH) $(INC_3D) $(INC_AUDIO) $(INC_WORKBENCH)

include $(TOP)/make_lib.mk
