# Makefile in FilePacker

PROGRAM=mFilePacker$(EXE)

INST_EXTRA=$(INST_EXTRA_DIR)

CXXFILES=src/filepacker.cpp src/main.cpp

INCLUDES=$(INC_CORE)

LIBRARIES=$(LIB_CORE) $(LIB_ZLIB)

include $(TOP)/make_prg.mk
