# Makefile in FontGenerator

PROGRAM=mFontGenerator$(EXE)

INST_EXTRA=$(INST_EXTRA_DIR)

CXXFILES=src/main.cpp

INCLUDES=$(INC_CORE) $(INC_MATH) $(INC_2D)

LIBRARIES=$(LIB_CORE) $(LIB_MATH)

include $(TOP)/make_prg.mk
