# Makefile in Math

LIB=$(LIB_MATH)

CXXFILES=src/aabb.cpp src/angles.cpp src/box2d.cpp src/collisioninfo2d.cpp \
	src/collisioninfo.cpp src/collisionmesh.cpp src/collisiontriangle.cpp \
	src/crypto.cpp src/cylinder.cpp src/ellipsoid.cpp src/frustum.cpp \
	src/hsv.cpp src/line.cpp src/mathfunc.cpp src/matrix.cpp src/noise.cpp \
	src/plane.cpp src/quat.cpp src/random.cpp src/ray.cpp src/segment2d.cpp \
	src/segment.cpp src/sphere.cpp src/triangle2d.cpp src/triangle.cpp \
	src/vector2.cpp src/vector4.cpp src/vector.cpp

INCLUDES=$(INC_CORE)

include $(TOP)/make_lib.mk
