# Makefile in ContentSyncer

PROGRAM=mContentSyncer$(EXE)

INST_EXTRA=$(INST_EXTRA_DIR)

CXXFILES=src/main.cpp

INCLUDES=(INC_2D) $(INC_CORE)

LIBRARIES=$(LIB_2D) $(LIB_CORE)

include $(TOP)/make_prg.mk
